### ISSUE TITLE
broken git history

### ISSUE THREAD

**Issue by blockparole** [SoiledCold5/Browncoin#4]
The git history is broken because the project wasnt properly forked from [litecoin-project/litecoin](https://github.com/litecoin-project/litecoin) (5a25916955b2cd694b1c2da821d23438a1774fc8).
Im not sure if its possible to change a github repo to a fork after it was created, so it might be needed to create another repository. This might be a good opportunity to move the repository from a user to an organization namespace.

**Comment by DarkiBoi** [comment]
yes this needs to be fixed

**Comment by SoiledCold5** [comment]
So I did look at the git, we didn't directly fork the litecoin project on github. I took a download of the git, edited it and uploaded it on github. I will bring this up to the other developers. Stay tuned.

**Comment by nothub** [comment]
you seem to have closed this by accident...
@SoiledCold5
